### Mathematical Operations

In [1]:
import numpy

In [9]:
a = numpy.array([1,2,3,4])
b = numpy.array([5,6,7,8])

In [10]:
a + b

array([ 6,  8, 10, 12])

In [11]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [12]:
b / a

array([5.        , 3.        , 2.33333333, 2.        ])

In [13]:
a - b

array([-4, -4, -4, -4])

In [14]:
a ** b

array([    1,    64,  2187, 65536])

In [15]:
a * b

array([ 5, 12, 21, 32])

In [16]:
str(a + b)

'[ 6  8 10 12]'

In [18]:
print(numpy.prod(numpy.sum(numpy.array([ [1, 2], [3, 4] ]), axis=0)))

24
